- frontend/src/pages/admin/CreateUser.tsx
- frontend/src/pages/admin/Users.tsx
This error appears and terminates request when trying to delete users that includes the logged-in user itself. This is a functional fix, the popup can be touched up later (This part of the site is concealed to admin's so design isn't concerning).
Fixes #9
> Don't allow logged-in admin to delete themselves

- frontend/src/components/Navigation.tsx
Fixed a PR #31 which was reverted during that PR.
Fixes #31
> Nav update

- frontend/package-lock.json
- frontend/package.json
- frontend/src/pages/Home.tsx
- frontend/src/pages/admin/EditProblem.tsx
- frontend/src/pages/admin/Home.tsx
- frontend/src/pages/admin/NewProblem.tsx
- frontend/src/pages/admin/Problems.tsx
- frontend/src/pages/admin/Submission.tsx
- frontend/src/pages/admin/Submissions.tsx
- frontend/src/pages/admin/UploadProblems.tsx
- frontend/src/pages/admin/UploadUsers.tsx
- frontend/src/pages/admin/Users.tsx
- frontend/src/pages/blue/Problem.tsx
- frontend/src/pages/blue/Problems.tsx
- frontend/src/pages/blue/Standings.tsx
- frontend/src/pages/blue/Submission.tsx
- frontend/src/pages/blue/Submissions.tsx
- frontend/src/pages/blue/Submit.tsx
- frontend/src/pages/gold/Connect.tsx
- frontend/src/pages/gold/Problem.tsx
- frontend/src/pages/gold/Problems.tsx
- frontend/src/pages/gold/Submission.tsx
- frontend/src/pages/gold/Submissions.tsx
- frontend/src/pages/gold/Submit.tsx
- frontend/src/types.d.ts
Created a new admin dashboard with graphs of submission data. Other updates included in this branch include:
- Updated names for Dynamo table calls
- Cleaned up request calls for data
- Fixed package vulnerability
- Fixed typos
> Admin dashboard

- frontend/src/pages/Home.tsx
Fixed issue where fetches were happening every 200ms for teams table on home page
> Fix fetch issues

- backend/package.json
> Javascript not typescript for start command

- backend/package.json
- package-lock.json
- package.json
> Backend fix

- backend/package-lock.json
- backend/package.json
- package-lock.json
- package.json
💰 THIS IS IT OR YOUR MONEY BACK 💰
> Backend fix2

- frontend/src/components/Countdown.tsx
Clear interval for updating the date in the Countdown component when the component is unmounted
* Potentially solves out of memory error with abacus
> Clear interval on unmount for countdown

- backend/package-lock.json
- frontend/package-lock.json
- frontend/src/pages/About.tsx
- frontend/src/pages/Help.tsx
- frontend/src/pages/blue/Home.tsx
- package-lock.json
Added FAQs and updated verbiage about the competition throughout the main pages of Abacus.
Fixes # (issue number)
> Polish main pages

- backend/src/api/submissions/postSubmissions.ts
- frontend/src/pages/blue/BlueNavigation.tsx
- frontend/src/pages/gold/GoldNavigation.tsx
Only show `problems`, `submissions`, and `clarifications` tabs on navbar for blue and gold if a user is an admin, judge, or team participating in that division
Fixes #56
> #56 conditionally show nav items based on user

- backend/src/api/problems/getProblems.ts
- backend/src/api/submissions/postSubmissions.ts
- frontend/package.json
- frontend/src/pages/admin/Home.tsx
- frontend/src/pages/admin/submissions/Submission.tsx
- frontend/src/pages/admin/submissions/Submissions.tsx
- frontend/src/pages/blue/BlueNavigation.tsx
- frontend/src/pages/blue/Problem.scss
- frontend/src/pages/blue/Problem.tsx
- frontend/src/pages/blue/Problems.tsx
- frontend/src/pages/blue/Submission.tsx
- frontend/src/pages/blue/Submissions.tsx
- frontend/src/pages/blue/Submit.tsx
- frontend/src/pages/blue/index.tsx
- frontend/src/pages/blue/practice/Problem.tsx
- frontend/src/pages/blue/practice/Submission.tsx
- frontend/src/pages/blue/practice/Submit.tsx
- frontend/src/pages/blue/practice/index.tsx
- frontend/src/pages/blue/practice/problem.json
- frontend/src/pages/gold/GoldNavigation.tsx
- frontend/src/pages/gold/Submission.tsx
- frontend/src/pages/gold/Submissions.tsx
- frontend/src/types.d.ts
- frontend/src/utils/index.ts
- frontend/yarn.lock
Practice subsection of the blue division page that is only visible before the competition starts. Allows users to try the platform to make sure it works before the competition starts, and that their computer is capable of using the platform.
Fixes #52
> #52 Practice problem

- frontend/public/problems/index.json
- frontend/src/pages/About.tsx
- frontend/src/pages/gold/Home.tsx
Updated Gold Division description and corrected years for the practice problems.
> Gold description

- frontend/src/pages/blue/Problem.tsx
Currently, the problem page shows a Not Found image while waiting for a response. This PR will show a loader instead while waiting, and if the problem comes back as not found then the Not Found image will show.
> Add loader while waiting from problem data

- frontend/src/pages/About.tsx
Updated wording for about section of the divisions.
> Updated wording

- frontend/src/pages/blue/Standings.tsx
> Errors with standings

- frontend/src/pages/admin/users/Users.tsx
Created a way for an Admin user to import users from the ACM website registration database. Included in this PR are also some small UI changes to the buttons on that page (added loading and disabled states).
> Created user importing from ACM Registration

- frontend/public/scratch-bookmarklet.js
- frontend/src/pages/gold/Home.tsx
Store the javascript code for the gold submit bookmarklet on codeabac.us rather than in the bookmarklet. 
This allows us to make changes to the bookmarklet code without forcing users to recreate the bookmark.
> Use codeabac.us for bookmarklet code.

- .github/PULL_REQUEST_TEMPLATE.md
Added an option to the PR template for code cleanup.
> Added code cleanup option

- frontend/src/components/Footer.tsx
Just a more friendly / trendy footer :)
> Footer update

- frontend/src/pages/admin/problems/Problems.tsx
- frontend/src/pages/admin/problems/UploadProblems.tsx
- frontend/src/pages/admin/users/UploadUsers.tsx
* Download all problem data from backend.
* Ignore checked property for both users and problems
* Show a warning message rather than table when no new data
Fixes #91
> Fix Bugs when Importing Users/Problems

- frontend/src/pages/blue/Problem.tsx
Only show Memory Limit and CPU Time Limit on the problem page if the problem has them.
> Only show memory and time limits if they exist

- frontend/src/components/editor/ProblemEditor.tsx
Error with ProblemEditor.tsx, causing app not to load. `useState` needs to be inside the function.
> BUG FIX - useState gotta be in in function

- frontend/src/pages/admin/Home.tsx
Fix a bug with the Admin Dashboard graphs when the numBuckets is not a whole number which causes the dashboard to crash.
> Fix bug with non whole number for numBuckets

- backend/src/api/standings/getStandings.ts
- frontend/src/pages/blue/Standings.tsx
Show the pending judgement question mark for submissions await judgement on the standings.
Also the standing page will refresh when a new submission is created.
> Show Pending for Standings

- backend/src/api/clarifications/postClarifications.ts
- frontend/src/pages/Clarifications.tsx
Validate clarifications to guarantee the titles / body are non-empty, non-whitespace text and contain real text.
Add Reply button also always stops loading after getting a response from the server.
> Clarifications title/body must include title/body

- backend/src/abacus/authlib.ts
- backend/src/abacus/contest.ts
- backend/src/api/clarifications/index.ts
- backend/src/api/contest/index.ts
- backend/src/api/problems/index.ts
- backend/src/api/submissions/getSubmissions.ts
- backend/src/api/submissions/index.ts
- backend/src/api/submissions/putSubmissions.ts
- backend/src/api/users/index.ts
- frontend/src/App.tsx
- frontend/src/components/index.ts
- frontend/src/components/submission/SubmissionDetail.tsx
- frontend/src/components/submission/SubmissionView.tsx
- frontend/src/components/submission/index.ts
- frontend/src/pages/admin/submissions/Submission.tsx
- frontend/src/pages/admin/users/EditUser.tsx
- frontend/src/pages/blue/Submission.tsx
- frontend/src/pages/gold/Submission.tsx
- frontend/src/pages/index.tsx
- frontend/src/pages/judge/Home.tsx
- frontend/src/pages/judge/JudgeNavigation.tsx
- frontend/src/pages/judge/Problem.scss
- frontend/src/pages/judge/Problem.tsx
- frontend/src/pages/judge/Problems.tsx
- frontend/src/pages/judge/Submission.tsx
- frontend/src/pages/judge/Submissions.tsx
- frontend/src/pages/judge/Users.tsx
- frontend/src/pages/judge/index.tsx
- frontend/src/types.d.ts
- frontend/src/utils/index.ts
Allows for the claiming and releasing of submissions for judging. Also introduces a judging portal which has more limited permissions than an Admin.
The judging portal is not entirely finished, but the code needs to be pushed for Blue Judge orientation tonight.
Fixes #116
> Blue Judging Capabilities

- frontend/src/components/editor/ProblemInfoEditor.tsx
Fixes naming issues for python and java solutions on a new problem creation.
> Fixed solution and skeleton naming issues

- frontend/src/App.tsx
Support other transports for socket.io
> support polling socket.io

- backend/src/abacus/contest.ts
- backend/src/api/submissions/deleteSubmissions.ts
- backend/src/api/submissions/getSubmissions.ts
- backend/src/api/submissions/postSubmissions.ts
- backend/src/api/submissions/putSubmissions.ts
get submissions is an all or nothing, so if a tid or claimed value doesn't have a corresponding user, the server returns with a `500` `Internal Server Error`
> Fix Bug where Claimed user is undefined

- frontend/src/App.scss
- frontend/src/App.tsx
- frontend/src/components/DivisionLabel.tsx
- frontend/src/pages/About.tsx
- frontend/src/pages/Eagle.tsx
- frontend/src/pages/Home.tsx
- frontend/src/pages/eagle/EagleNavigation.tsx
- frontend/src/pages/eagle/Home.tsx
- frontend/src/pages/eagle/Problem.tsx
- frontend/src/pages/eagle/index.tsx
- frontend/src/pages/index.tsx
- frontend/src/utils/index.ts
Eagle division was revamped to match the structure of the other divisions.
> Eagle Division Revamp

- frontend/src/pages/blue/Problem.tsx
- frontend/src/pages/blue/Problems.tsx
- frontend/src/pages/blue/Standings.tsx
- frontend/src/pages/blue/Submission.tsx
- frontend/src/pages/blue/Submissions.tsx
- frontend/src/pages/blue/Submit.tsx
- frontend/src/pages/eagle/Problem.tsx
- frontend/src/pages/gold/Problem.tsx
- frontend/src/pages/gold/Problems.tsx
- frontend/src/pages/gold/Standings.tsx
- frontend/src/pages/gold/Submission.tsx
- frontend/src/pages/gold/Submissions.tsx
- frontend/src/pages/gold/Submit.tsx
These changes are to protect certain pages against users without certain credentials from accessing them. This is important so that students cannot share URLs to problems with those who are not in their division and do not have an account.
> Page Authentication

- frontend/src/components/editor/ProblemInfoEditor.tsx
- frontend/src/pages/admin/problems/Problems.tsx
- frontend/src/pages/eagle/Problem.tsx
This change allows for an Eagle division problem to be created by an admin, viewed by judges and teams, and hidden from outside users. This allows for a more dynamic competition.
> Eagle Revamp

- frontend/src/pages/Home.tsx
- frontend/src/pages/blue/Rules.tsx
Added welcome video and fixed a bug in the rules.
> Updated rules and header for homepage

- frontend/package.json
- frontend/src/pages/admin/Home.tsx
- frontend/src/pages/admin/users/Users.tsx
- frontend/src/pages/judge/Users.tsx
- Deleted @toast-ui as a package
- error message now are seen as strings
- Abacus should compile successfully now
Fixes # ([175](https://github.com/acm-mu/abacus/issues/175))
- run the instructions setup in the README to install Abacus locally, upon doing them the site should load successfully.
- [] My changes do not break any features.
<PieChart Component deleted ^>
> Fixed errors associated with react-chart, as well as error messages not being seen as strings

- .github/ISSUE_TEMPLATE/documentation.md
- documentation category added to issues
Fixes issue # [185](https://github.com/acm-mu/abacus/issues/185)
> created category in issues for documentation

- README.md
> READme now includes the process of creating a new branch

- .github/workflows/deploy-frontend-docker.yml
Add a GitHub Workflow to build and push the production Docker image of the frontend to the GitHub Container Registry.
> Add Docker build and publish workflow for the frontend

- backend/src/api/clarifications/getClarifications.ts
- backend/src/api/clarifications/index.ts
- backend/src/api/submissions/getSubmissions.ts
- backend/src/api/users/getUsers.ts
- frontend/src/pages/Clarifications.tsx
- frontend/src/pages/admin/Clarifications.tsx
- this makes it so clarifications are now functional on local!
Fixes #231 
- adding a clarification as a admin or a judge should result in a clarification being added to the table.
> clarifications should be functional now

- frontend/src/components/CustomTable/CustomTable.scss
- frontend/src/components/CustomTable/index.tsx
- frontend/src/pages/admin/problems/Problems.tsx
- frontend/src/pages/admin/users/Users.tsx
- frontend/tsconfig.json
- package.json
- yarn.lock
- custom table for the users table, will need to make a component for each table, due to how each is customized
Fixes #241
> check out custom user table

- backend/src/api/submissions/rerunSubmission.ts
- frontend/src/components/CustomTable/index.tsx
- frontend/src/pages/blue/practice/Problem.tsx
- frontend/src/pages/judge/Problems.tsx
- frontend/src/pages/judge/Submissions.tsx
- frontend/src/pages/judge/Users.tsx
Fixes n/a
- problems, submissions and users should render now on judge pages
> Judge table render

- .github/CODEOWNERS
- .github/workflows/ci-test-backend.yml
- .github/workflows/ci-test-frontend.yml
Add Code ownership so that original authors must review new code being merged into master
> Add codeowners
