acm-mu/abacus

backend/api/contest.ts, frontend/src/pages/admin/Settings.tsx
This change stops admins from changing the end date to before the start date on a backend level. The frontend will now show errors (and success) when saving settings.
Fixes #11 
I tested this change by using Postman to send requests to the backend where the dates were reversed and received an error in response, no database change occurred. I also tried a valid date configuration and the database updated. I then proceeded to try these same tests through the user interface
=> Backend prevent change end date before start date

frontend/src/components/Navigation.tsx
The redirect was not happening because the username onClick was firing first and beating the handleLogout redirect. Create a 20ms delay on the handleLogout redirect.
Fixes #28
=> Redirect milliseconds after logging out #28

frontend/src/components/Countdown.tsx
Fixed flip clock not displaying for situations when the contest had not started.
=> Fixed logic for clock before start date

backend/package.json
AWS backend was trying to ts-node src/server.js for prod environment. Src directory does not exist, and ts-node is not installed.
This fix uses node with the compiled source instead.
Fixes # (issue number)
=> Use node instead of ts-node for prod start command

backend/src/api/submissions/postSubmissions.ts
Send 400 status code when trying to submit to a problem before or after the competition.
Fixes #39 
Changed the competition around and tested sending a submission before, during, and after. The submission was only allowed to go through during the competition time.
=> #39 Dont allow submissions before or after competition

backend/src/@types/abacus/index.d.ts, backend/src/api/problems/postProblems.ts, frontend/src/pages/admin/problems/EditProblem.tsx, frontend/src/pages/admin/problems/NewProblem.tsx, frontend/src/pages/admin/problems/Problems.tsx, frontend/src/pages/admin/submissions/Submission.tsx, frontend/src/pages/admin/users/Users.tsx, frontend/src/pages/blue/practice/problem.json, frontend/src/types.d.ts
* Adds `file_name` property to skeletons for download skeleton files
* Particularly necessary for Java source files where class name and filename need to match
* Filename defaults to problem name (without spaces or special characters) when creating new problems
* Remove `checked` from users when downloading as JSON
* Download all data about problems when downloading as JSON  
* Allow downloading submission's source code for local testing as a fallback.
Fixes #52
* Users.json includes checked property
* Download all problem data when exporting
* Add download button for individual submissions
* `file_name` property for submissions
=> File names for skeletons

backend/src/@types/abacus/index.d.ts, backend/src/api/submissions/getSubmissions.ts, backend/src/api/submissions/postSubmissions.ts, backend/src/api/submissions/putSubmissions.ts, frontend/src/pages/admin/submissions/Submission.tsx, frontend/src/pages/admin/submissions/Submissions.tsx, frontend/src/pages/blue/practice/Submit.tsx, frontend/src/types.d.ts
- Submissions are unreleased (`released` = `false`) by default
- Team's submissions and submission view will not show results until submission is released
- New column in admin submissions view for released status
- Table can filter out released submissions
- Submission view for admins has a release button to release results to the team. (Can't be unrelease)
- Release button along with rerun now shows loader when waiting for network response
Fixes #50
=> Release submissions (#50)

frontend/src/App.scss, frontend/src/pages/admin/submissions/Submissions.tsx
- Fixes bug with toggle released on admin submissions page
- Auto refreshes submissions while on admin submissions page
Fixes Toggle to hide and show released submissions
Auto-refreshes submissions page for admins
=> Toggle released & Auto refresh for submissions

backend/src/api/clarifications/postClarifications.ts, backend/src/api/clarifications/putClarifications.ts
When creating public clarifications, admins are presented with an invalid value error. This is because the backend requests a `context` to be provided. 
This PR will make `context` optional for clarifications.
<!x- This not the same as a **Breaking Change**. You have tested that all other features are not affected by this change. -->
=> Fix a bug when creating public clarifications

frontend/src/components/submission/SubmissionDetail.tsx
Problems with links on submission pages. 
- Prepending an extra `/` to the front of the url links to another website not a page on the current website. 
- There was an extra `{` in the submission link
- Problem was linking to pid and not problem id. Router doesn't know how to resolve pid
Fixes #132 
Fixes #133
=> Fix broken links on submission page

frontend/src/components/editor/TestDataEditor.tsx
Set a fixed text area height with `rows={int}`. Rather than adjusting based on content which led to shrinking on character action
Fixes #134
=> Fixed TextArea height for TestData

frontend/src/components/ScratchViewer.tsx, frontend/src/pages/blue/Problem.tsx
Fix links for scratch projects, and sample files. 
Use an `<a>` tag instead of `<Link>` tag for external links.
=> External Links should use <a> tags

frontend/src/components/submission/SubmissionDetail.tsx
Differentiate between roles for links to problems. Problem link's for teams use the short ID, but admins use the entire problem pid because short_ids can duplicate across divisions.
=> Fix broken link for admin submission view

backend/src/api/submissions/getSubmissions.ts, frontend/src/pages/judge/Home.tsx
Fix a bug where claimed does not properly send to the frontend with user details, and properly bucket submissions in the right table on the judge homepage.
=> Fix resolving claimee for submissions & Bucket submissions correctly on judge home

backend/src/abacus/contest.ts, backend/src/api/submissions/deleteSubmissions.ts, backend/src/api/submissions/getSubmissions.ts, backend/src/api/submissions/postSubmissions.ts, backend/src/api/submissions/putSubmissions.ts, frontend/src/pages/admin/submissions/Submissions.tsx
* When using the check all button, only visible submissions are updated.
* When clicking delete selected, only include checked and visible submissions.
Fixes #147
=> Only delete submissions if they are checked and visible (#147)

frontend/src/components/Notifications.tsx
When the notification listener is checking if the notification is for them, it does not refresh if the user state changes.
These changes refresh the listener when the user state changes.
=> Refresh notification listener when user changes.

backend/src/server.ts
Allow clients to broadcast messages to other clients by implementing a boomerang broadcast handler in `server.ts` that will use the data to send a broadcast event to all clients.
Example use
`socket.emit('broadcast', {ev: 'EVENT_NAME', args: {EVENT_DATA}})`
This will allow the lambda function `PistonRunner` to broadcast `update_submission` after grading submissions.
=> Allow clients to broadcast messages

backend/src/@types/abacus/index.d.ts, backend/src/api/standings/getStandings.ts, backend/src/api/submissions/getSubmissions.ts, backend/src/api/submissions/postSubmissions.ts, backend/src/api/submissions/putSubmissions.ts, backend/src/api/users/putUsers.ts, frontend/src/App.scss, frontend/src/pages/admin/Home.tsx, frontend/src/pages/admin/users/EditUser.tsx, frontend/src/pages/admin/users/Users.tsx, frontend/src/pages/blue/Standings.tsx, frontend/src/pages/blue/Submit.tsx, frontend/src/pages/judge/Home.tsx, frontend/src/pages/judge/Submission.tsx, frontend/src/pages/judge/Submissions.tsx, frontend/src/types.d.ts
- Allow admins to disable users
- Prevent from showing in standings
- Prevent future submissions
- Prevent from showing on flagged submissions (admin dashboard)
- Prevent from showing on judging dashboard   
* Submit page blocks disabled teams from submitting and teams with unreleased or pending submissions.
* Judge dashboard is limited to 5 submissions per section
* Submission headers link to judge submissions table applying filter
* Judge submission page only shows buttons they can use
* backend prevents judges from claiming already claimed submissions.
Fixes #100 
Fixes #115
=> Disable user

.github/workflows/ci-prettier.yml
DevOps Bug Fix. 
Prettier GitHub action cannot push to master because it is protected and requires peer reviews. Instead, run this action on every branch except master. By the time it a PR is created, prettier should have run.
This has not been tested, buyers beware!
=> 🧰 Prettier Fix

.github/workflows/deploy-backend-docker.yml
Add a GitHub Workflow to build and push the production Docker image of the backend to the GitHub Container Registry.
=> Add workflow to deploy Abacus backend to GHCR

frontend/src/context/socket.ts, frontend/tsconfig.json
* Following Socket.io's [Migrating from 3.x to 4.0](https://socket.io/docs/v4/migrating-from-3-x-to-4-0/#typed-events) guide, defined client to server events on the frontend to conform to the socket io type definition.
* Upgraded tsconfig target to `es6` (`es5` does not have `class` keyword, which `Socket` is, so compilation error that `Socket` is not a type is because babel transpiles it down to a `function`)
Fixes #207 
* Compiles to build, and runs locally
=> Socket io types

.github/workflows/deploy-backend-docker.yml, .github/workflows/deploy-frontend-docker.yml
Add `latest` tag to docker deployments along with github sha to identify docker images.
Currently the remote package is labeled with the branch (`master`) so the command has to be
`docker pull ghcr.io/acm-mu/abacus-frontend:master`
With this change, the tag will not be needed (because `latest` is inferred) and instead the command will be 
`docker pull ghcr.io/acm-mu/abacus-frontend`
=> 🏷️ Add latest tag to docker GHCR deployments

backend/src/api/submissions/putSubmissions.ts, backend/src/services/db/mongo.ts
* Specifically check for `undefined` or `null` values when unsettling fields in mongo update operation.
* Update submission improperly retrieves submission using non-existent `id`.
Fixes #217 
* Tested updating problem with `practice` field to boolean value that reproduces error described in #217  issue.
=> 🔧 MongoDB Update Item Patch

frontend/public/index.html, frontend/src/App.scss
The background color and some other CSS properties are being overridden by a newer version of Semantic UI.
=> Fix app styling being overridden by Semantic UI

frontend/src/pages/gold/Standings.tsx
The Problem Id links on the gold standings page link to blue problems. This is incorrect behavior and should link to gold problems instead.
=> 🐞 Fix Problem Links in Gold Standings
